
name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - README.md

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Set up golang env
        id: go_env
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/checkout@v2

      - name: Get dependencies
        run: go get

      - name:
        run: go test -v

